# Change prefix to ctrl-a
unbind C-b
set -g prefix C-s
bind C-s send-prefix

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Setting for mouse
set -g mouse on

# Gruvbox Theme
source-file "~/.config/tmux/gruvbox-theme-tmux.conf"

# Start windows and pane at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


# VIM mode
set -g mode-keys vi

# Move between panes with vi keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

## Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

## reset status intervar time
set -g status-interval 5
########### END

# Set new panes to open in current directory
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

##avoiddelaytime
set -sg escape-time 10

# because neovim wants it
set-option -g focus-events on

# Titles 
set -g set-titles on
set -g set-titles-string "#T"

set -g default-command "/bin/fish -i"



